# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

    # install yq and change version
      - name: yq - install
        uses: mikefarah/yq@v4.44.1

      - name: yq change version
        working-directory: ./manifest_files
        run: yq -i '.spec.template.spec.containers.image = "70"' deployment.yaml

    # commit         
      - name: Add & Commit           
        uses: EndBug/add-and-commit@v9.1.4
        with:
          author_name: talshaham
          author_email: talso12345@gmail.com
          commit: --signoff
          message: 'changing version'

